package tool

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strings"

	"golang.org/x/mod/modfile"

	"github.com/goccy/tobari/internal/utils"
	"github.com/goccy/tobari/internal/version"
)

func buildPackages(workDir string, ver *version.Version, lang string, opts BuildOpts) (map[string]string, error) {
	appDir := utils.WorkAppDir(workDir)
	// Skip createApp if the directory was already prepared by a prior toolexec
	// invocation in the same build (same $WORK).
	if _, err := os.Stat(filepath.Join(appDir, "go.sum")); err != nil {
		if err := createApp(appDir, ver, lang); err != nil {
			return nil, fmt.Errorf("failed to create temp app: %w", err)
		}
	}

	toolexec, err := tobariToolexec(opts)
	if err != nil {
		return nil, err
	}

	// Use go list -deps -export with -toolexec=tobari to compile and get export paths
	// for github.com/goccy/tobari and all its transitive dependencies.
	//
	// The temp app's go.mod ensures the correct version of tobari is resolved:
	//   - Released version: require github.com/goccy/tobari <version>
	//   - Development:      replace github.com/goccy/tobari => <local path>
	//   - Forked module:    require plus replace onto the replacement module
	//
	// Using Go's build cache paths directly (instead of building separate archives)
	// guarantees that compile and link steps always reference the same package files,
	// preventing fingerprint mismatches when Go's build cache replays cached results.
	// When the outer build uses -trimpath, passing -trimpath here ensures the inner
	// build produces packages in the same cache entries as the outer build.
	pkgs, err := utils.GoListDepsExport(appDir, utils.GoListOpts{
		Toolexec:  toolexec,
		Trimpath:  opts.Trimpath,
		Race:      opts.Race,
		BuildTags: opts.BuildTags,
	}, "github.com/goccy/tobari")
	if err != nil {
		return nil, fmt.Errorf("failed to get tobari packages: %w", err)
	}
	return pkgs, nil
}

func createApp(appDir string, ver *version.Version, lang string) error {
	if err := os.MkdirAll(appDir, 0o755); err != nil {
		return fmt.Errorf("failed to create %s: %w", appDir, err)
	}
	if err := createGoMod(filepath.Join(appDir, "go.mod"), ver, lang); err != nil {
		return err
	}
	if err := createMain(filepath.Join(appDir, "main.go")); err != nil {
		return err
	}
	if err := utils.GoModTidy(appDir); err != nil {
		return err
	}
	return nil
}

func createGoMod(path string, ver *version.Version, lang string) error {
	f := new(modfile.File)
	if err := f.AddModuleStmt("tobari"); err != nil {
		return fmt.Errorf("failed to add module stmt: %w", err)
	}
	goVer := lang
	if goVer == "" {
		v, err := utils.GoVersion()
		if err != nil {
			v = runtime.Version()
		}
		goVer = v
	}
	goVer = strings.TrimPrefix(goVer, "go")
	if err := f.AddGoStmt(goVer); err != nil {
		return fmt.Errorf("failed to add go stmt: %w", err)
	}
	if ver.LocalPath != "" {
		// Use the absolute path in the replace directive. A relative path
		// would have to be computed against the go.mod's directory, but Go
		// resolves the module root through symlinks (e.g. macOS's
		// /var -> /private/var for $WORK under $TMPDIR), so a lexically
		// correct relative path can point at the wrong directory. The temp
		// module is ephemeral and never leaves this machine, so an absolute
		// path is both safe and unambiguous.
		if err := f.AddReplace("github.com/goccy/tobari", "", ver.LocalPath, ""); err != nil {
			return fmt.Errorf("failed to add replace directive: %w", err)
		}
	} else {
		if err := f.AddRequire("github.com/goccy/tobari", ver.Ver); err != nil {
			return fmt.Errorf("failed to add require directive: %w", err)
		}
		if ver.ReplacePath != "" {
			// The version belongs to the replacement's repository, so the
			// require above cannot be resolved on its own: asking the proxy
			// for that version of github.com/goccy/tobari finds no such
			// revision. The replace has to come along for this module to
			// resolve to the same tobari the outer build resolves to.
			if err := f.AddReplace("github.com/goccy/tobari", "", ver.ReplacePath, ver.Ver); err != nil {
				return fmt.Errorf("failed to add replace directive: %w", err)
			}
		}
	}
	data, err := f.Format()
	if err != nil {
		return fmt.Errorf("failed to format go.mod: %w", err)
	}
	if err := os.WriteFile(path, data, 0o600); err != nil {
		return fmt.Errorf("failed to write go.mod to %s: %w", path, err)
	}
	return nil
}

func createMain(path string) error {
	content := `
// Code generated by tobari. DO NOT EDIT!
package main
import _ "github.com/goccy/tobari"
func main() {}
`
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		return fmt.Errorf("failed to write main.go to %s: %w", path, err)
	}
	return nil
}
